<% @ Control  Language="C#" Inherits="PageAdmin.paform"%>
<% @ Import NameSpace="System.Data"%>
<% @ Import NameSpace="System.Data.OleDb"%>
<%Start();%>
<tr id='tr_download_title'><td class='tdhead'>文件名称<span style='color:#ff0000'>*</span></td><td><input type=text name='title' id='title' value="<%if(post=="add"){Response.Write("");}else{Response.Write(r("title"));}%>" size="40" maxlength="200"><span id="title_tip"></span></td></tr>
<tr id='tr_download_pa_jj'><td class='tdhead' id='tr_download_pa_jj'>简介</td><td><textarea name='pa_jj' id='pa_jj' style='width:400px'   ><%if(post=="add"){Response.Write("");}else{Response.Write(r("pa_jj"));}%></textarea><span id="pa_jj_tip"></span></td></tr>
<tr id='tr_download_titlepic'><td class='tdhead'>附件缩略图</td><td><input ondblclick="if(this.value!='')window.open(this.value)" type=text name='titlepic' id='titlepic'  value="<%if(post=="add"){Response.Write("");}else{Response.Write(r("titlepic"));}%>" size="50" ><%if(Field_ImageUpload=="true"){%><a href="javascript:delete_file('download','titlepic',<%=InforId%>)" id="delete_titlepic" style="padding-left:2px;display:<%=r("titlepic")==""?"none":""%>" title='删除图片'><img src=/e/images/public/del.gif border=0></a><a id='upload_titlepic' href="javascript:open_upload('<%=SiteId%>','','image','download','titlepic','titlepic')" style="display:<%=r("titlepic")==""?"":"none"%>"><img src='/e/images/public/attachimg.gif' border=0  hspace=2 alt='上传图片' align=absbottom></a><%}%><span id="titlepic_tip"></span></td></tr><tr id='tr_download_pa_author'><td class='tdhead'>作者/发布人<span style='color:#ff0000'>*</span></td><td><input type=text name='pa_author' id='pa_author' value="<%if(post=="add"){Response.Write("");}else{Response.Write(r("pa_author"));}%>"  maxlength="200"><span id="pa_author_tip"></span></td></tr>
<tr id='tr_download_pa_size'><td class='tdhead'>文件大小<span style='color:#ff0000'>*</span></td><td><input type=text name='pa_size' id='pa_size' value="<%if(post=="add"){Response.Write("");}else{Response.Write(r("pa_size"));}%>"  maxlength="200"><span id="pa_size_tip"> 单位m</span></td></tr>
<tr id='tr_download_pa_yxhj'><td class='tdhead'>运行环境<span style='color:#ff0000'>*</span></td><td> <input type=checkbox  value="Win9x" name='pa_yxhj' id='pa_yxhj'>Win9x <input type=checkbox  value="NT" name='pa_yxhj' id='pa_yxhj'>NT <input type=checkbox  value="Win2000" name='pa_yxhj' id='pa_yxhj'>Win2000 <input type=checkbox  value="WinXP" name='pa_yxhj' id='pa_yxhj'>WinXP <input type=checkbox  value="Win2003" name='pa_yxhj' id='pa_yxhj'>Win2003 <input type=checkbox  value="Win7" name='pa_yxhj' id='pa_yxhj'>Win7 <input type=checkbox  value="unix" name='pa_yxhj' id='pa_yxhj'>unix<span id="pa_yxhj_tip"></span><%if(post=="add"){%><script type="text/javascript">Set_Checked("Win9x,NT,Win2000,WinXP,Win2003,Win7","pa_yxhj")</script><%}else{%><script type="text/javascript">Set_Checked("<%=r("pa_yxhj")%>","pa_yxhj")</script><%}%></td></tr><tr id='tr_download_pa_geshi'><td class='tdhead'>文件格式<span style='color:#ff0000'>*</span></td><td><select name='pa_geshi' id='pa_geshi'   ><option value="rar">rar压缩包</option><option value="zip">zip压缩包</option><option value="doc">word文档</option><option value="xls">excel文档</option><option value="pdf">pdf文档</option><option value="ppt">ppt文档</option><option value="file">其他格式</option></select><span id="pa_geshi_tip"></span><%if(post=="add"){%><script type="text/javascript">Set_Selected("","pa_geshi")</script><%}else{%><script type="text/javascript">Set_Selected("<%=r("pa_geshi")%>","pa_geshi")</script><%}%></td></tr><tr id='tr_download_pa_jspass'><td class='tdhead'>解压密码</td><td><input type=text name='pa_jspass' id='pa_jspass' value="<%if(post=="add"){Response.Write("");}else{Response.Write(r("pa_jspass"));}%>"  maxlength="200"><span id="pa_jspass_tip"></span></td></tr>
<tr id='tr_download_pa_sqfs'><td class='tdhead'>授权方式<span style='color:#ff0000'>*</span></td><td><select name='pa_sqfs' id='pa_sqfs'   ><option value="免费版">免费版</option><option value="共享版">共享版</option><option value="适用版">适用版</option></select><span id="pa_sqfs_tip"></span><%if(post=="add"){%><script type="text/javascript">Set_Selected("免费版","pa_sqfs")</script><%}else{%><script type="text/javascript">Set_Selected("<%=r("pa_sqfs")%>","pa_sqfs")</script><%}%></td></tr><tr id='tr_download_pa_fj'><td class='tdhead'>附件组<span style='color:#ff0000'>*</span><br><input type='button' value='增加文件' class='f_bt' onclick="open_files('<%=SiteId%>','0','download','pa_fj','files','<%=InforId%>')"><br><input type='button' id='Edit_pa_fj' value='刷新文件' class='f_bt' onclick="Iframe_Submit('iframe_pa_fj')" style='display:none'></td><td><div id='pa_fj_box' style='width:98%;border:1px solid #cccccc;background-color:#ffffff;padding:5px 5px 5px 5px'><input type=hidden value='0' name='pa_fj' id='pa_fj'><iframe  id='iframe_pa_fj' name='iframe_pa_fj' allowtransparency='true' src='/e/aspx/file_list.aspx?id=<%=InforId%>&table=download&field=pa_fj&fieldtype=files&sid=<%=SiteId%>&from=member' frameborder=0 scroling=auto height=150px width=100% marginwidth=0 marginheight=0 align=center></iframe></div><span id="pa_fj_tip"></span></td></tr><tr id='tr_download_content'><td class='tdhead'>附件介绍<span style='color:#ff0000'>*</span></td><td><textarea name='content' id='content' style="width:100%;height:300px"   ><%if(post=="add"){Response.Write("");}else{Response.Write(r("content"));}%></textarea><script charset="utf-8" src="/e/incs/kindeditor/kindeditor.js" type="text/javascript"></script><script type="text/javascript">var KE_content;KindEditor.ready(function(K) {KE_content= K.create("#content",{uploadJson :kindeditor_uploadJson,fileManagerJson :kindeditor_fileManagerJson,allowImageUpload:<%=Editor_ImageUpload%>,allowFlashUpload:<%=Editor_FlashUpload%>,allowMediaUpload:<%=Editor_FlashUpload%>,allowFileUpload:<%=Editor_AttachmentUpload%>,allowFileManager :false,items :kindeditor_SimpleItems,filterMode :false,extraFileUploadParams:{siteid:"<%=SiteId%>"}});});</script><span id="content_tip"></span></td></tr>
<tr id='tr_download_thedate'><td class='tdhead'>发布日期<span style='color:#ff0000'>*</span></td><td><input type=text name='thedate' id='thedate' value="<%if(post=="add"){Response.Write(""==""?DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"):"");}else{Response.Write(DateTime.Parse(r("thedate")).ToString("yyyy-MM-dd HH:mm:ss"));}%>"  maxlength="200"><a href="javascript:open_calendar('thedate',1)"><img src=/e/images/icon/date.gif border=0 height=20 hspace=2 align=absbottom></a><span id="thedate_tip"></span></td></tr>

<input type='hidden' name='mustname' value='文件名称,作者/发布人,文件大小,运行环境,文件格式,授权方式,附件组,附件介绍,发布日期,'><input type='hidden' name='mustfield' value='title,pa_author,pa_size,pa_yxhj,pa_geshi,pa_sqfs,pa_fj,content,thedate,'><input type='hidden' name='musttype' value='text,text,text,checkbox,select,select,files,editor,text,'>
<script  type='text/javascript'>
function download_zdycheck(){
Iframe_Submit("iframe_pa_fj","1")
KE_content.sync();
return true;
}
</script>
<%End();%>






